# Generated by Django 4.1.7 on 2023-02-27 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(max_length=20)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='capital_market.teams')),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('primary_email', models.CharField(max_length=20, null=True)),
                ('secondary_email', models.CharField(max_length=200, null=True)),
                ('primary_phone', models.CharField(max_length=20, null=True)),
                ('secondary_phone', models.CharField(max_length=20, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capital_market.applications')),
                ('primary_cont_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_cont_person', to='capital_market.teammembers')),
                ('secondary_cont_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_cont_person', to='capital_market.teammembers')),
            ],
        ),
    ]
