# Generated by Django 4.1.7 on 2023-02-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital_market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembers',
            name='is_teamleader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='position',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Sr.Software Engineer', 'Sr.Software Engineer'), ('Software Engineer', 'Software Engineer'), ('Jr.Software Engineer', 'Jr.Software Engineer'), ('Intern', 'Intern')], default=0, max_length=30),
            preserve_default=False,
        ),
    ]
