# Generated by Django 4.1.7 on 2023-03-06 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capital_market', '0002_teammembers_is_teamleader_teammembers_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='contact_person_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='is_dealer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clients',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='capital_market.applications'),
        ),
    ]
