# Generated by Django 4.1.7 on 2023-03-06 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capital_market', '0003_clients_contact_person_name_clients_is_dealer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='capital_market.applications'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='primary_cont_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_cont_person', to='capital_market.teammembers'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='secondary_cont_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_cont_person', to='capital_market.teammembers'),
        ),
    ]
