# Generated by Django 4.1.7 on 2023-03-06 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capital_market', '0004_alter_clients_application_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammembers',
            old_name='application',
            new_name='team',
        ),
    ]
