# Generated by Django 4.1.7 on 2023-03-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital_market', '0006_alter_clients_contact_person_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='primary_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
